version: '3.8'

services:
  msvc_config:
    container_name: msvc_config
    image: msvc-config-app:1.0.0
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dasv21
      POSTGRES_PASSWORD: dasv21
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

