server:
  port: 8383

spring:
  application:
    name: msvc-authentication
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://authentication-db:5432/authenticationDB
    username: dasv21
    password: dasv21
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: msvc-authentication
  client:
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka