eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: accountant
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/accountant/**
        - id: client
          uri: http://localhost:9191
          predicates:
            - Path=/api/v1/client/**
        - id: bill
          uri: http://localhost:9393
          predicates:
            - Path=/api/v1/bill/**
