eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:

        - id: accountant
          uri: lb://msvc-accountant
          predicates:
            - Path=/api/v1/accountant/**
          filters:
            - AuthenticationFilter

        - id: client
          uri: lb://msvc-client
          predicates:
            - Path=/api/v1/client/**
          filters:
            - AuthenticationFilter

        - id: bill
          uri: lb://msvc-bill
          predicates:
            - Path=/api/v1/bill/**
          filters:
            - AuthenticationFilter

        - id: authentication
          uri: lb://msvc-authentication
          predicates:
            - Path=/api/v1/auth/**