server:
  port: 9393

spring:
  application:
    name: msvc-bill
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://bill-db:5432/billDB
    username: dasv21
    password: dasv21
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: msvc-bill
  client:
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka