
server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000" # Aquí tienes que colocar la ruta de la app que va a consumir tus APIs
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - HEAD
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Authorization"
              - "Cache-Control"
              - "Content-Type"
              - "Access-Control-Allow-Origin"
            allowCredentials: true

      routes:

        - id: msvc-accountant
          uri: lb://msvc-accountant
          predicates:
            - Path=/api/v1/accountant/**
          filters:
            - AuthenticationFilter

        - id: msvc-client
          uri: lb://msvc-client
          predicates:
            - Path=/api/v1/client/**
          filters:
            - AuthenticationFilter

        - id: msvc-bill
          uri: lb://msvc-bill
          predicates:
            - Path=/api/v1/bill/**
          filters:
            - AuthenticationFilter

        - id: msvc-authentication
          uri: lb://msvc-authentication
          predicates:
            - Path=/api/v1/auth/**
      discovery:
         locator:
           enable: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://msvc-eureka:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework: INFO