eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000" # Aquí tienes que colocar la ruta de la app que va a consumir tus APIs
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - HEAD
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Authorization"
              - "Cache-Control"
              - "Content-Type"
              - "Access-Control-Allow-Origin"
            allowCredentials: true

      discovery:
        locator:
          enable: true
      routes:

        - id: accountant
          uri: lb://msvc-accountant
          predicates:
            - Path=/api/v1/accountant/**
          #filters:
          #  - AuthenticationFilter # Este es el filtro de autenticacion desativado mientras hago las patallas

        - id: client
          uri: lb://msvc-client
          predicates:
            - Path=/api/v1/client/**
          #filters:
          #  - AuthenticationFilter

        - id: bill
          uri: lb://msvc-bill
          predicates:
            - Path=/api/v1/bill/**
          #filters:
          #  - AuthenticationFilter

        - id: authentication
          uri: lb://msvc-authentication
          predicates:
            - Path=/api/v1/auth/**