server:
  port: 8761

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: msvc_eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    sever-url:
      defaultZone: http://msvc_eureka:${server.port}/eureka/